# Generated by Django 4.2.4 on 2023-08-15 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="imagem",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
