# Generated by Django 4.2.4 on 2023-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("models", "0002_veiculo_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="imagem",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="imagem",
            field=models.ManyToManyField(to="uploader.image"),
        ),
    ]
