# Generated by Django 4.2.4 on 2023-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0003_remove_veiculo_imagem_veiculo_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
    ]
