# Generated by Django 4.2.4 on 2023-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0004_alter_veiculo_preco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
