# Generated by Django 4.2.4 on 2023-08-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0005_alter_veiculo_preco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="cor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculo",
                to="models.cor",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculo",
                to="models.acessorio",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculo",
                to="models.modelo",
            ),
        ),
    ]
